import type { Product } from "./types"

// Starter catalog. Partition key = category, sort key = productId.
export const SEED_PRODUCTS: Product[] = [
  // ---------------- Headphones ----------------
  {
    category: "Headphones",
    productId: "aurorasound-pro",
    name: "AuroraSound Pro Wireless Headphones",
    brand: "AuroraSound",
    description:
      "Over-ear noise cancelling wireless headphones with 40-hour battery life and studio-grade sound.",
    price: 279,
    originalPrice: 329,
    rating: 4.7,
    reviewCount: 2143,
    features: ["Active noise cancelling", "40h battery", "Bluetooth 5.3", "Multipoint pairing"],
    tags: ["noise-cancelling", "premium", "travel"],
    imageUrl: "/products/aurorasound-pro.png",
    inStock: true,
  },
  {
    category: "Headphones",
    productId: "aurorasound-air",
    name: "AuroraSound Air Earbuds",
    brand: "AuroraSound",
    description: "Compact true-wireless earbuds with adaptive ANC and a pocketable charging case.",
    price: 129,
    originalPrice: 149,
    rating: 4.4,
    reviewCount: 1582,
    features: ["Adaptive ANC", "28h total battery", "IPX4 water resistant", "Wireless charging"],
    tags: ["earbuds", "budget", "workout"],
    imageUrl: "/products/aurorasound-air.png",
    inStock: true,
  },
  {
    category: "Headphones",
    productId: "pulsebeat-studio",
    name: "PulseBeat Studio Headphones",
    brand: "PulseBeat",
    description: "Audiophile open-back headphones tuned for detailed, natural sound at home.",
    price: 199,
    rating: 4.5,
    reviewCount: 874,
    features: ["Open-back design", "Detachable cable", "Plush memory foam", "Wide soundstage"],
    tags: ["audiophile", "home", "wired"],
    imageUrl: "/products/pulsebeat-studio.png",
    inStock: true,
  },
  {
    category: "Headphones",
    productId: "junior-beats-kids",
    name: "JuniorBeats Kids Headphones",
    brand: "JuniorBeats",
    description: "Colorful, volume-limited wireless headphones sized and tuned for kids' safe listening.",
    price: 39,
    originalPrice: 49,
    rating: 4.6,
    reviewCount: 3045,
    features: ["85dB volume limit", "Kid-sized fit", "24h battery", "Durable build"],
    tags: ["kids", "budget", "party"],
    imageUrl: "/products/junior-beats-kids.png",
    inStock: true,
  },

  // ---------------- Speakers ----------------
  {
    category: "Speakers",
    productId: "partypulse-360",
    name: "PartyPulse 360 Bluetooth Speaker",
    brand: "PartyPulse",
    description: "Loud 360-degree party speaker with pulsing LED lights and a 24-hour battery.",
    price: 149,
    originalPrice: 199,
    rating: 4.6,
    reviewCount: 2710,
    features: ["360° sound", "LED light show", "24h battery", "IPX6 splashproof"],
    tags: ["party", "music", "portable"],
    imageUrl: "/products/partypulse-360.png",
    inStock: true,
  },
  {
    category: "Speakers",
    productId: "basscube-party",
    name: "BassCube Party Speaker",
    brand: "BassCube",
    description: "High-power party speaker with deep bass, disco lights, and a wireless mic input.",
    price: 229,
    originalPrice: 279,
    rating: 4.5,
    reviewCount: 1320,
    features: ["120W output", "Disco light effects", "Mic & guitar inputs", "Wheels & handle"],
    tags: ["party", "music", "karaoke"],
    imageUrl: "/products/basscube-party.png",
    inStock: true,
  },
  {
    category: "Speakers",
    productId: "soundorb-mini",
    name: "SoundOrb Mini Portable Speaker",
    brand: "SoundOrb",
    description: "Pocket-sized speaker with surprisingly big sound and a clip for on-the-go music.",
    price: 49,
    originalPrice: 69,
    rating: 4.3,
    reviewCount: 4188,
    features: ["Clip-on design", "12h battery", "Waterproof", "Stereo pairing"],
    tags: ["budget", "music", "portable"],
    imageUrl: "/products/soundorb-mini.png",
    inStock: true,
  },

  // ---------------- Laptops ----------------
  {
    category: "Laptops",
    productId: "nimbusbook-14",
    name: "NimbusBook 14 Laptop",
    brand: "Nimbus",
    description:
      "Ultralight 14-inch laptop with all-day battery and a bright OLED display for work and travel.",
    price: 1199,
    originalPrice: 1399,
    rating: 4.6,
    reviewCount: 1320,
    features: ['14" OLED display', "18h battery", "16GB RAM", "512GB SSD"],
    tags: ["ultrabook", "work", "premium"],
    imageUrl: "/products/nimbusbook-14.png",
    inStock: true,
  },
  {
    category: "Laptops",
    productId: "nimbusbook-go",
    name: "NimbusBook Go 13",
    brand: "Nimbus",
    description: "Budget-friendly everyday laptop that handles browsing, docs, and streaming with ease.",
    price: 649,
    originalPrice: 729,
    rating: 4.2,
    reviewCount: 945,
    features: ['13" IPS display', "12h battery", "8GB RAM", "256GB SSD"],
    tags: ["budget", "student", "everyday"],
    imageUrl: "/products/nimbusbook-go.png",
    inStock: true,
  },
  {
    category: "Laptops",
    productId: "vertex-creator-16",
    name: "Vertex Creator 16 Laptop",
    brand: "Vertex",
    description: "Powerful 16-inch creator laptop with a discrete GPU for editing and design workloads.",
    price: 1899,
    rating: 4.8,
    reviewCount: 612,
    features: ['16" 165Hz display', "RTX GPU", "32GB RAM", "1TB SSD"],
    tags: ["creator", "gaming", "performance"],
    imageUrl: "/products/vertex-creator.png",
    inStock: true,
  },

  // ---------------- Tablets ----------------
  {
    category: "Tablets",
    productId: "slate-10",
    name: "Slate 10 Tablet",
    brand: "Slate",
    description: "Versatile 10-inch tablet for streaming, reading, and browsing with a crisp display.",
    price: 329,
    originalPrice: 379,
    rating: 4.4,
    reviewCount: 1502,
    features: ['10.5" display', "12h battery", "128GB storage", "Quad speakers"],
    tags: ["everyday", "entertainment", "portable"],
    imageUrl: "/products/slate-10.png",
    inStock: true,
  },
  {
    category: "Tablets",
    productId: "slate-kids",
    name: "Slate Kids Tablet",
    brand: "Slate",
    description: "Kid-proof tablet with a bumper case, parental controls, and a year of learning content.",
    price: 149,
    originalPrice: 179,
    rating: 4.5,
    reviewCount: 2890,
    features: ["Shockproof case", "Parental controls", "Kid content included", "10h battery"],
    tags: ["kids", "gift", "learning"],
    imageUrl: "/products/slate-kids.png",
    inStock: true,
  },

  // ---------------- Wearables ----------------
  {
    category: "Wearables",
    productId: "trailblaze-watch",
    name: "TrailBlaze GPS Running Watch",
    brand: "TrailBlaze",
    description: "Multisport GPS watch with heart-rate, sleep tracking, and a 2-week battery.",
    price: 249,
    originalPrice: 299,
    rating: 4.5,
    reviewCount: 1788,
    features: ["Dual-band GPS", "14-day battery", "HR & SpO2", "100+ sport modes"],
    tags: ["fitness", "outdoor", "gps"],
    imageUrl: "/products/trailblaze-watch.png",
    inStock: true,
  },
  {
    category: "Wearables",
    productId: "trailblaze-lite",
    name: "TrailBlaze Lite Fitness Band",
    brand: "TrailBlaze",
    description: "Slim activity band with all-day tracking, notifications, and a budget price.",
    price: 59,
    originalPrice: 79,
    rating: 4.1,
    reviewCount: 2401,
    features: ["7-day battery", "Step & sleep tracking", "Phone notifications", "Water resistant"],
    tags: ["budget", "fitness", "everyday"],
    imageUrl: "/products/trailblaze-lite.png",
    inStock: true,
  },
  {
    category: "Wearables",
    productId: "junior-fit-kids",
    name: "JuniorFit Kids Smartwatch",
    brand: "JuniorFit",
    description: "Playful kids smartwatch with games, step tracking, a camera, and fun watch faces.",
    price: 49,
    originalPrice: 69,
    rating: 4.2,
    reviewCount: 1975,
    features: ["Built-in games", "Step tracking", "Camera", "Colorful faces"],
    tags: ["kids", "gift", "fun"],
    imageUrl: "/products/junior-fit-kids.png",
    inStock: true,
  },

  // ---------------- Monitors ----------------
  {
    category: "Monitors",
    productId: "lumaview-27-4k",
    name: "LumaView 27 4K Monitor",
    brand: "LumaView",
    description: "Color-accurate 27-inch 4K monitor with USB-C charging, ideal for creative work.",
    price: 449,
    originalPrice: 549,
    rating: 4.6,
    reviewCount: 733,
    features: ['27" 4K UHD', "99% sRGB", "90W USB-C", "Height adjustable"],
    tags: ["creator", "office", "usb-c"],
    imageUrl: "/products/lumaview-27.png",
    inStock: true,
  },
  {
    category: "Monitors",
    productId: "lumaview-play-27",
    name: "LumaView Play 27 Gaming Monitor",
    brand: "LumaView",
    description: "Fast 165Hz QHD gaming monitor with low latency and vivid contrast.",
    price: 329,
    rating: 4.4,
    reviewCount: 988,
    features: ['27" QHD', "165Hz refresh", "1ms response", "HDR400"],
    tags: ["gaming", "performance", "high-refresh"],
    imageUrl: "/products/lumaview-play.png",
    inStock: true,
  },

  // ---------------- Gaming ----------------
  {
    category: "Gaming",
    productId: "pixelplay-handheld",
    name: "PixelPlay Handheld Console",
    brand: "PixelPlay",
    description: "Portable gaming handheld with a vivid screen and a library of family-friendly games.",
    price: 199,
    originalPrice: 249,
    rating: 4.5,
    reviewCount: 1640,
    features: ['7" HD screen', "8h playtime", "Couch co-op", "Huge game library"],
    tags: ["gaming", "gift", "fun"],
    imageUrl: "/products/pixelplay-handheld.png",
    inStock: true,
  },
  {
    category: "Gaming",
    productId: "pixelplay-controller",
    name: "PixelPlay Wireless Controller",
    brand: "PixelPlay",
    description: "Ergonomic wireless controller with low-latency response and customizable buttons.",
    price: 59,
    rating: 4.4,
    reviewCount: 2210,
    features: ["Low latency", "40h battery", "Hall-effect sticks", "Custom buttons"],
    tags: ["gaming", "accessory", "fun"],
    imageUrl: "/products/pixelplay-controller.png",
    inStock: true,
  },
  {
    category: "Gaming",
    productId: "nova-vr-headset",
    name: "Nova VR Headset",
    brand: "Nova",
    description: "Standalone VR headset with crisp lenses and a growing library of immersive games.",
    price: 399,
    originalPrice: 449,
    rating: 4.3,
    reviewCount: 905,
    features: ["Standalone (no PC)", "4K per eye", "Hand tracking", "Wireless"],
    tags: ["gaming", "premium", "immersive"],
    imageUrl: "/products/nova-vr-headset.png",
    inStock: true,
  },

  // ---------------- Cameras ----------------
  {
    category: "Cameras",
    productId: "snapjoy-instant",
    name: "SnapJoy Instant Print Camera",
    brand: "SnapJoy",
    description: "Fun instant camera that prints photos on the spot — perfect for parties and events.",
    price: 79,
    originalPrice: 99,
    rating: 4.6,
    reviewCount: 3560,
    features: ["Instant prints", "Selfie mirror", "Built-in flash", "Fun filters"],
    tags: ["party", "gift", "fun"],
    imageUrl: "/products/snapjoy-instant.png",
    inStock: true,
  },
  {
    category: "Cameras",
    productId: "actionpro-x",
    name: "ActionPro X Action Camera",
    brand: "ActionPro",
    description: "Rugged 4K action camera with stabilization for capturing adventures and events.",
    price: 249,
    originalPrice: 299,
    rating: 4.5,
    reviewCount: 1428,
    features: ["4K60 video", "Waterproof", "Image stabilization", "Voice control"],
    tags: ["outdoor", "video", "gift"],
    imageUrl: "/products/actionpro-x.png",
    inStock: true,
  },

  // ---------------- Smart Home ----------------
  {
    category: "Smart Home",
    productId: "glowlate-party-lights",
    name: "GlowLate Smart Party Lights",
    brand: "GlowLate",
    description: "Color-changing smart lights that sync to music — set the mood for any celebration.",
    price: 69,
    originalPrice: 89,
    rating: 4.5,
    reviewCount: 2630,
    features: ["16M colors", "Music sync", "App & voice control", "Easy peel-and-stick"],
    tags: ["party", "smart-home", "ambiance"],
    imageUrl: "/products/glowlate-party-lights.png",
    inStock: true,
  },
  {
    category: "Smart Home",
    productId: "nestguard-cam",
    name: "NestGuard Security Camera",
    brand: "NestGuard",
    description: "1080p indoor security camera with night vision, motion alerts, and two-way audio.",
    price: 49,
    originalPrice: 69,
    rating: 4.3,
    reviewCount: 4015,
    features: ["1080p HD", "Night vision", "Motion alerts", "Two-way audio"],
    tags: ["smart-home", "security", "everyday"],
    imageUrl: "/products/nestguard-cam.png",
    inStock: true,
  },
  {
    category: "Smart Home",
    productId: "robovac-go",
    name: "RoboVac Go Robot Vacuum",
    brand: "RoboVac",
    description: "Smart robot vacuum with app mapping and scheduling — great for pre- and post-party cleanup.",
    price: 199,
    originalPrice: 259,
    rating: 4.4,
    reviewCount: 1890,
    features: ["Smart mapping", "App scheduling", "Auto-recharge", "Quiet mode"],
    tags: ["smart-home", "cleaning", "everyday"],
    imageUrl: "/products/robovac-go.png",
    inStock: true,
  },

  // ---------------- Home & Kitchen ----------------
  {
    category: "Home",
    productId: "brewmaster-smart",
    name: "BrewMaster Smart Coffee Maker",
    brand: "BrewMaster",
    description: "App-controlled drip coffee maker with scheduling and precise temperature control.",
    price: 159,
    originalPrice: 189,
    rating: 4.3,
    reviewCount: 1106,
    features: ["App scheduling", "Precise temp control", "Thermal carafe", "Auto-clean"],
    tags: ["kitchen", "smart-home", "everyday"],
    imageUrl: "/products/brewmaster.png",
    inStock: true,
  },
  {
    category: "Home",
    productId: "aerochef-compact",
    name: "AeroChef Compact Air Fryer",
    brand: "AeroChef",
    description: "Space-saving 4-quart air fryer with presets for quick, crispy meals.",
    price: 89,
    originalPrice: 119,
    rating: 4.6,
    reviewCount: 3210,
    features: ["4qt capacity", "8 presets", "Dishwasher-safe basket", "Rapid heat"],
    tags: ["kitchen", "budget", "everyday"],
    imageUrl: "/products/aerochef.png",
    inStock: true,
  },
  {
    category: "Home",
    productId: "blendmax-pro",
    name: "BlendMax Pro Blender",
    brand: "BlendMax",
    description: "Powerful countertop blender for smoothies, party drinks, and frozen treats.",
    price: 119,
    originalPrice: 149,
    rating: 4.5,
    reviewCount: 2044,
    features: ["1200W motor", "6 presets", "Self-clean", "64oz pitcher"],
    tags: ["kitchen", "party", "drinks"],
    imageUrl: "/products/blendmax-pro.png",
    inStock: true,
  },
  {
    category: "Home",
    productId: "fizzmaker-soda",
    name: "FizzMaker Sparkling Drink Maker",
    brand: "FizzMaker",
    description: "Turn tap water into sparkling soda in seconds — a hit for parties and gatherings.",
    price: 99,
    originalPrice: 129,
    rating: 4.4,
    reviewCount: 1567,
    features: ["No batteries needed", "Fizz control", "Reusable bottles", "Compact"],
    tags: ["kitchen", "party", "drinks"],
    imageUrl: "/products/fizzmaker-soda.png",
    inStock: true,
  },
]
