import type { Product } from "./types"

// Starter catalog. Partition key = category, sort key = productId.
export const SEED_PRODUCTS: Product[] = [
  {
    category: "Headphones",
    productId: "aurorasound-pro",
    name: "AuroraSound Pro Wireless Headphones",
    brand: "AuroraSound",
    description:
      "Over-ear noise cancelling wireless headphones with 40-hour battery life and studio-grade sound.",
    price: 279,
    originalPrice: 329,
    rating: 4.7,
    reviewCount: 2143,
    features: ["Active noise cancelling", "40h battery", "Bluetooth 5.3", "Multipoint pairing"],
    tags: ["noise-cancelling", "premium", "travel"],
    imageUrl: "/products/aurorasound-pro.png",
    inStock: true,
  },
  {
    category: "Headphones",
    productId: "aurorasound-air",
    name: "AuroraSound Air Earbuds",
    brand: "AuroraSound",
    description: "Compact true-wireless earbuds with adaptive ANC and a pocketable charging case.",
    price: 129,
    originalPrice: 149,
    rating: 4.4,
    reviewCount: 1582,
    features: ["Adaptive ANC", "28h total battery", "IPX4 water resistant", "Wireless charging"],
    tags: ["earbuds", "budget", "workout"],
    imageUrl: "/products/aurorasound-air.png",
    inStock: true,
  },
  {
    category: "Headphones",
    productId: "pulsebeat-studio",
    name: "PulseBeat Studio Headphones",
    brand: "PulseBeat",
    description: "Audiophile open-back headphones tuned for detailed, natural sound at home.",
    price: 199,
    rating: 4.5,
    reviewCount: 874,
    features: ["Open-back design", "Detachable cable", "Plush memory foam", "Wide soundstage"],
    tags: ["audiophile", "home", "wired"],
    imageUrl: "/products/pulsebeat-studio.png",
    inStock: true,
  },
  {
    category: "Laptops",
    productId: "nimbusbook-14",
    name: "NimbusBook 14 Laptop",
    brand: "Nimbus",
    description:
      "Ultralight 14-inch laptop with all-day battery and a bright OLED display for work and travel.",
    price: 1199,
    originalPrice: 1399,
    rating: 4.6,
    reviewCount: 1320,
    features: ['14" OLED display', "18h battery", "16GB RAM", "512GB SSD"],
    tags: ["ultrabook", "work", "premium"],
    imageUrl: "/products/nimbusbook-14.png",
    inStock: true,
  },
  {
    category: "Laptops",
    productId: "nimbusbook-go",
    name: "NimbusBook Go 13",
    brand: "Nimbus",
    description: "Budget-friendly everyday laptop that handles browsing, docs, and streaming with ease.",
    price: 649,
    originalPrice: 729,
    rating: 4.2,
    reviewCount: 945,
    features: ['13" IPS display', "12h battery", "8GB RAM", "256GB SSD"],
    tags: ["budget", "student", "everyday"],
    imageUrl: "/products/nimbusbook-go.png",
    inStock: true,
  },
  {
    category: "Laptops",
    productId: "vertex-creator-16",
    name: "Vertex Creator 16 Laptop",
    brand: "Vertex",
    description: "Powerful 16-inch creator laptop with a discrete GPU for editing and design workloads.",
    price: 1899,
    rating: 4.8,
    reviewCount: 612,
    features: ['16" 165Hz display', "RTX GPU", "32GB RAM", "1TB SSD"],
    tags: ["creator", "gaming", "performance"],
    imageUrl: "/products/vertex-creator.png",
    inStock: true,
  },
  {
    category: "Wearables",
    productId: "trailblaze-watch",
    name: "TrailBlaze GPS Running Watch",
    brand: "TrailBlaze",
    description: "Multisport GPS watch with heart-rate, sleep tracking, and a 2-week battery.",
    price: 249,
    originalPrice: 299,
    rating: 4.5,
    reviewCount: 1788,
    features: ["Dual-band GPS", "14-day battery", "HR & SpO2", "100+ sport modes"],
    tags: ["fitness", "outdoor", "gps"],
    imageUrl: "/products/trailblaze-watch.png",
    inStock: true,
  },
  {
    category: "Wearables",
    productId: "trailblaze-lite",
    name: "TrailBlaze Lite Fitness Band",
    brand: "TrailBlaze",
    description: "Slim activity band with all-day tracking, notifications, and a budget price.",
    price: 59,
    originalPrice: 79,
    rating: 4.1,
    reviewCount: 2401,
    features: ["7-day battery", "Step & sleep tracking", "Phone notifications", "Water resistant"],
    tags: ["budget", "fitness", "everyday"],
    imageUrl: "/products/trailblaze-lite.png",
    inStock: true,
  },
  {
    category: "Monitors",
    productId: "lumaview-27-4k",
    name: "LumaView 27 4K Monitor",
    brand: "LumaView",
    description: "Color-accurate 27-inch 4K monitor with USB-C charging, ideal for creative work.",
    price: 449,
    originalPrice: 549,
    rating: 4.6,
    reviewCount: 733,
    features: ['27" 4K UHD', "99% sRGB", "90W USB-C", "Height adjustable"],
    tags: ["creator", "office", "usb-c"],
    imageUrl: "/products/lumaview-27.png",
    inStock: true,
  },
  {
    category: "Monitors",
    productId: "lumaview-play-27",
    name: "LumaView Play 27 Gaming Monitor",
    brand: "LumaView",
    description: "Fast 165Hz QHD gaming monitor with low latency and vivid contrast.",
    price: 329,
    rating: 4.4,
    reviewCount: 988,
    features: ['27" QHD', "165Hz refresh", "1ms response", "HDR400"],
    tags: ["gaming", "performance", "high-refresh"],
    imageUrl: "/products/lumaview-play.png",
    inStock: true,
  },
  {
    category: "Home",
    productId: "brewmaster-smart",
    name: "BrewMaster Smart Coffee Maker",
    brand: "BrewMaster",
    description: "App-controlled drip coffee maker with scheduling and precise temperature control.",
    price: 159,
    originalPrice: 189,
    rating: 4.3,
    reviewCount: 1106,
    features: ["App scheduling", "Precise temp control", "Thermal carafe", "Auto-clean"],
    tags: ["kitchen", "smart-home", "everyday"],
    imageUrl: "/products/brewmaster.png",
    inStock: true,
  },
  {
    category: "Home",
    productId: "aerochef-compact",
    name: "AeroChef Compact Air Fryer",
    brand: "AeroChef",
    description: "Space-saving 4-quart air fryer with presets for quick, crispy meals.",
    price: 89,
    originalPrice: 119,
    rating: 4.6,
    reviewCount: 3210,
    features: ["4qt capacity", "8 presets", "Dishwasher-safe basket", "Rapid heat"],
    tags: ["kitchen", "budget", "everyday"],
    imageUrl: "/products/aerochef.png",
    inStock: true,
  },
]
