import type { Product } from "./types"

// Event-planning catalog. Partition key = category, sort key = productId.
export const SEED_PRODUCTS: Product[] = [
  // ---------------- Decorations ----------------
  {
    category: "Decorations",
    productId: "balloon-arch-kit",
    name: "DIY Balloon Arch Kit",
    brand: "FestaCo",
    description:
      "130-piece balloon garland kit in mixed pastels with strip tape and tools for a stunning party backdrop.",
    price: 19,
    originalPrice: 26,
    rating: 4.6,
    reviewCount: 4120,
    features: ["130 balloons", "Decorating strip", "Glue dots", "Reusable"],
    tags: ["birthday", "backdrop", "diy"],
    imageUrl: "/products/balloon-arch-kit.png",
    inStock: true,
  },
  {
    category: "Decorations",
    productId: "happy-birthday-banner",
    name: "Happy Birthday Foil Banner",
    brand: "FestaCo",
    description: "Reusable rose-gold foil 'Happy Birthday' banner that hangs in seconds for any age.",
    price: 9,
    originalPrice: 13,
    rating: 4.5,
    reviewCount: 2870,
    features: ["Pre-strung", "Reusable", "Rose gold foil", "No assembly"],
    tags: ["birthday", "wall", "budget"],
    imageUrl: "/products/happy-birthday-banner.png",
    inStock: true,
  },
  {
    category: "Decorations",
    productId: "led-fairy-lights",
    name: "LED Fairy String Lights (2-Pack)",
    brand: "GlowNest",
    description: "Two 33ft warm-white battery string lights to add a cozy glow to any celebration.",
    price: 14,
    originalPrice: 19,
    rating: 4.7,
    reviewCount: 5310,
    features: ["66ft total", "Battery powered", "8 light modes", "Bendable wire"],
    tags: ["ambiance", "lighting", "indoor"],
    imageUrl: "/products/led-fairy-lights.png",
    inStock: true,
  },
  {
    category: "Decorations",
    productId: "paper-lanterns",
    name: "Hanging Paper Lantern Set",
    brand: "FestaCo",
    description: "Assorted-size round paper lanterns in bright colors to fill a room with festive flair.",
    price: 16,
    rating: 4.3,
    reviewCount: 1240,
    features: ["12 lanterns", "3 sizes", "Collapsible", "Reusable"],
    tags: ["colorful", "ceiling", "reusable"],
    imageUrl: "/products/paper-lanterns.png",
    inStock: true,
  },

  // ---------------- Food & Supplies ----------------
  {
    category: "Food & Supplies",
    productId: "party-plates-set",
    name: "Party Plates & Cups Set (Service for 24)",
    brand: "ServeWell",
    description: "Coordinated disposable plates, cups, and bowls for 24 guests — sturdy and leak-resistant.",
    price: 21,
    originalPrice: 28,
    rating: 4.5,
    reviewCount: 3380,
    features: ["Serves 24", "Sturdy paper", "Plates + cups + bowls", "Microwave safe"],
    tags: ["tableware", "essentials", "bulk"],
    imageUrl: "/products/party-plates-set.png",
    inStock: true,
  },
  {
    category: "Food & Supplies",
    productId: "plastic-tablecloths",
    name: "Disposable Table Cover 4-Pack",
    brand: "ServeWell",
    description: "Four water-resistant plastic tablecloths that wipe clean and make cleanup effortless.",
    price: 12,
    originalPrice: 16,
    rating: 4.4,
    reviewCount: 2105,
    features: ["4 covers", "54\" x 108\"", "Water resistant", "Easy cleanup"],
    tags: ["tables", "cleanup", "essentials"],
    imageUrl: "/products/plastic-tablecloths.png",
    inStock: true,
  },
  {
    category: "Food & Supplies",
    productId: "cutlery-set",
    name: "Party Cutlery Set (96 Pieces)",
    brand: "ServeWell",
    description: "96-piece heavy-duty disposable forks, knives, and spoons — enough for a big gathering.",
    price: 11,
    rating: 4.3,
    reviewCount: 1760,
    features: ["96 pieces", "Heavy duty", "Forks/knives/spoons", "BPA-free"],
    tags: ["tableware", "bulk", "essentials"],
    imageUrl: "/products/cutlery-set.png",
    inStock: true,
  },
  {
    category: "Food & Supplies",
    productId: "paper-napkins",
    name: "Colorful Paper Napkins (200 ct)",
    brand: "ServeWell",
    description: "Soft 3-ply napkins in a rainbow of colors to brighten the table and handle spills.",
    price: 8,
    originalPrice: 11,
    rating: 4.6,
    reviewCount: 2940,
    features: ["200 count", "3-ply", "Assorted colors", "Absorbent"],
    tags: ["tableware", "budget", "essentials"],
    imageUrl: "/products/paper-napkins.png",
    inStock: true,
  },

  // ---------------- Party Favors ----------------
  {
    category: "Party Favors",
    productId: "goodie-bags",
    name: "Goodie Bag Favor Kit (24 Pack)",
    brand: "JoyBox",
    description: "24 pre-filled treat bags with small toys and stickers — grab-and-go thank-you favors.",
    price: 23,
    originalPrice: 30,
    rating: 4.4,
    reviewCount: 1890,
    features: ["24 bags", "Pre-filled", "Toys + stickers", "Kid favorites"],
    tags: ["kids", "favors", "thank-you"],
    imageUrl: "/products/goodie-bags.png",
    inStock: true,
  },
  {
    category: "Party Favors",
    productId: "bubble-wands",
    name: "Bubble Wand Party Pack (24)",
    brand: "JoyBox",
    description: "24 colorful bubble wands that double as fun activity and easy take-home favors.",
    price: 13,
    originalPrice: 18,
    rating: 4.7,
    reviewCount: 4015,
    features: ["24 wands", "Pre-filled solution", "No-spill caps", "Outdoor fun"],
    tags: ["kids", "outdoor", "favors"],
    imageUrl: "/products/bubble-wands.png",
    inStock: true,
  },
  {
    category: "Party Favors",
    productId: "mini-toy-assortment",
    name: "Mini Toy Favor Assortment (50 pc)",
    brand: "JoyBox",
    description: "50 assorted mini toys — yo-yos, slinkies, and puzzles — perfect for prize bins and bags.",
    price: 17,
    rating: 4.2,
    reviewCount: 1330,
    features: ["50 toys", "Variety pack", "Prize-bin ready", "All ages"],
    tags: ["kids", "prizes", "favors"],
    imageUrl: "/products/mini-toy-assortment.png",
    inStock: true,
  },
  {
    category: "Party Favors",
    productId: "sticker-sheets",
    name: "Sticker Sheet Bulk Pack",
    brand: "JoyBox",
    description: "Over 1,000 fun stickers across 50 sheets — a low-cost crowd-pleaser for any party.",
    price: 9,
    originalPrice: 12,
    rating: 4.6,
    reviewCount: 2560,
    features: ["1000+ stickers", "50 sheets", "Assorted themes", "Budget pick"],
    tags: ["kids", "budget", "favors"],
    imageUrl: "/products/sticker-sheets.png",
    inStock: true,
  },

  // ---------------- Games & Activities ----------------
  {
    category: "Games & Activities",
    productId: "pinata",
    name: "Pull-String Party Piñata",
    brand: "FiestaPlay",
    description: "Colorful pull-string piñata (no swinging needed) that holds plenty of candy and toys.",
    price: 22,
    originalPrice: 29,
    rating: 4.5,
    reviewCount: 1670,
    features: ["Pull-string safe", "Holds 2 lbs", "16\" tall", "Easy to fill"],
    tags: ["kids", "centerpiece", "classic"],
    imageUrl: "/products/pinata.png",
    inStock: true,
  },
  {
    category: "Games & Activities",
    productId: "ring-toss",
    name: "Outdoor Ring Toss Game Set",
    brand: "FiestaPlay",
    description: "Wooden ring toss set for backyards and BBQs — easy for kids and adults to enjoy.",
    price: 27,
    originalPrice: 34,
    rating: 4.4,
    reviewCount: 980,
    features: ["Wooden build", "All ages", "Indoor/outdoor", "Carry bag"],
    tags: ["outdoor", "bbq", "lawn-game"],
    imageUrl: "/products/ring-toss.png",
    inStock: true,
  },
  {
    category: "Games & Activities",
    productId: "face-paint-kit",
    name: "Kids Face Paint Kit",
    brand: "FiestaPlay",
    description: "Non-toxic 16-color face paint kit with brushes and stencils for instant party fun.",
    price: 18,
    originalPrice: 24,
    rating: 4.6,
    reviewCount: 3120,
    features: ["16 colors", "Non-toxic", "Brushes + stencils", "Easy wash-off"],
    tags: ["kids", "activity", "creative"],
    imageUrl: "/products/face-paint-kit.png",
    inStock: true,
  },
  {
    category: "Games & Activities",
    productId: "bean-bag-toss",
    name: "Bean Bag Toss Game",
    brand: "FiestaPlay",
    description: "Foldable cornhole-style bean bag toss with 8 bags — a hit at outdoor gatherings.",
    price: 32,
    rating: 4.3,
    reviewCount: 740,
    features: ["Foldable boards", "8 bean bags", "Portable", "All ages"],
    tags: ["outdoor", "bbq", "lawn-game"],
    imageUrl: "/products/bean-bag-toss.png",
    inStock: true,
  },

  // ---------------- Movie Night ----------------
  {
    category: "Movie Night",
    productId: "popcorn-machine",
    name: "Tabletop Popcorn Maker",
    brand: "CozyReel",
    description: "Retro hot-air popcorn machine that pops a big fresh batch in minutes — oil-free.",
    price: 39,
    originalPrice: 49,
    rating: 4.5,
    reviewCount: 2230,
    features: ["Hot-air popping", "Oil-free", "Fast batches", "Easy clean"],
    tags: ["movie", "snacks", "family"],
    imageUrl: "/products/popcorn-machine.png",
    inStock: true,
  },
  {
    category: "Movie Night",
    productId: "projector-screen",
    name: "Portable Projector Screen 100\"",
    brand: "CozyReel",
    description: "Wrinkle-free 100-inch projector screen for backyard movie nights and game days.",
    price: 33,
    originalPrice: 45,
    rating: 4.4,
    reviewCount: 1410,
    features: ["100\" diagonal", "Wrinkle-free", "Indoor/outdoor", "Foldable"],
    tags: ["movie", "outdoor", "entertainment"],
    imageUrl: "/products/projector-screen.png",
    inStock: true,
  },
  {
    category: "Movie Night",
    productId: "cozy-blanket-set",
    name: "Plush Throw Blanket Set (2-Pack)",
    brand: "CozyReel",
    description: "Two ultra-soft fleece throws to keep everyone snug during the feature presentation.",
    price: 29,
    originalPrice: 39,
    rating: 4.7,
    reviewCount: 3650,
    features: ["2 throws", "Ultra-soft fleece", "50\" x 60\"", "Machine washable"],
    tags: ["movie", "cozy", "indoor"],
    imageUrl: "/products/cozy-blanket-set.png",
    inStock: true,
  },
  {
    category: "Movie Night",
    productId: "snack-variety-box",
    name: "Movie Snack Variety Box",
    brand: "CozyReel",
    description: "A 40-count mix of popcorn, candy, and chips — instant concession stand for movie night.",
    price: 25,
    originalPrice: 32,
    rating: 4.4,
    reviewCount: 2880,
    features: ["40 snacks", "Sweet & salty mix", "Individually wrapped", "Crowd pleaser"],
    tags: ["movie", "snacks", "variety"],
    imageUrl: "/products/snack-variety-box.png",
    inStock: true,
  },
]
